# Generated by Django 5.0.7 on 2024-07-18 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidpaste", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Paste",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="post",
            new_name="paste",
        ),
    ]
