# Generated by Django 5.0.7 on 2024-07-18 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voidpaste", "0002_rename_post_paste_rename_post_comment_paste"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paste",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
