# Generated by Django 5.0.7 on 2024-07-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("voidpaste", "0003_alter_paste_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
